/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated.calendar'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated.sessions.index'
import { Route as AuthenticatedSessionsCreateRouteImport } from './routes/_authenticated.sessions.create'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated.sessions.$id'
import { Route as AuthenticatedDashboardManagerRouteImport } from './routes/_authenticated.dashboard.manager'
import { Route as AuthenticatedDashboardEntrepreneurRouteImport } from './routes/_authenticated.dashboard.entrepreneur'
import { Route as AuthenticatedDashboardCoachRouteImport } from './routes/_authenticated.dashboard.coach'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated.dashboard.admin'
import { Route as AuthenticatedSessionsIdEditRouteImport } from './routes/_authenticated.sessions.$id.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsCreateRoute =
  AuthenticatedSessionsCreateRouteImport.update({
    id: '/sessions/create',
    path: '/sessions/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardManagerRoute =
  AuthenticatedDashboardManagerRouteImport.update({
    id: '/manager',
    path: '/manager',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardEntrepreneurRoute =
  AuthenticatedDashboardEntrepreneurRouteImport.update({
    id: '/entrepreneur',
    path: '/entrepreneur',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCoachRoute =
  AuthenticatedDashboardCoachRouteImport.update({
    id: '/coach',
    path: '/coach',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedSessionsIdEditRoute =
  AuthenticatedSessionsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSessionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/dashboard/entrepreneur': typeof AuthenticatedDashboardEntrepreneurRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRouteWithChildren
  '/sessions/create': typeof AuthenticatedSessionsCreateRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/sessions/$id/edit': typeof AuthenticatedSessionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/dashboard/entrepreneur': typeof AuthenticatedDashboardEntrepreneurRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRouteWithChildren
  '/sessions/create': typeof AuthenticatedSessionsCreateRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/sessions/$id/edit': typeof AuthenticatedSessionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/_authenticated/dashboard/entrepreneur': typeof AuthenticatedDashboardEntrepreneurRoute
  '/_authenticated/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRouteWithChildren
  '/_authenticated/sessions/create': typeof AuthenticatedSessionsCreateRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/sessions/$id/edit': typeof AuthenticatedSessionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/calendar'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/coach'
    | '/dashboard/entrepreneur'
    | '/dashboard/manager'
    | '/sessions/$id'
    | '/sessions/create'
    | '/sessions'
    | '/sessions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/calendar'
    | '/dashboard'
    | '/dashboard/admin'
    | '/dashboard/coach'
    | '/dashboard/entrepreneur'
    | '/dashboard/manager'
    | '/sessions/$id'
    | '/sessions/create'
    | '/sessions'
    | '/sessions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/coach'
    | '/_authenticated/dashboard/entrepreneur'
    | '/_authenticated/dashboard/manager'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/sessions/create'
    | '/_authenticated/sessions/'
    | '/_authenticated/sessions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/create': {
      id: '/_authenticated/sessions/create'
      path: '/sessions/create'
      fullPath: '/sessions/create'
      preLoaderRoute: typeof AuthenticatedSessionsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager': {
      id: '/_authenticated/dashboard/manager'
      path: '/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof AuthenticatedDashboardManagerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/entrepreneur': {
      id: '/_authenticated/dashboard/entrepreneur'
      path: '/entrepreneur'
      fullPath: '/dashboard/entrepreneur'
      preLoaderRoute: typeof AuthenticatedDashboardEntrepreneurRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/coach': {
      id: '/_authenticated/dashboard/coach'
      path: '/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof AuthenticatedDashboardCoachRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/sessions/$id/edit': {
      id: '/_authenticated/sessions/$id/edit'
      path: '/edit'
      fullPath: '/sessions/$id/edit'
      preLoaderRoute: typeof AuthenticatedSessionsIdEditRouteImport
      parentRoute: typeof AuthenticatedSessionsIdRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardCoachRoute: typeof AuthenticatedDashboardCoachRoute
  AuthenticatedDashboardEntrepreneurRoute: typeof AuthenticatedDashboardEntrepreneurRoute
  AuthenticatedDashboardManagerRoute: typeof AuthenticatedDashboardManagerRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardCoachRoute: AuthenticatedDashboardCoachRoute,
    AuthenticatedDashboardEntrepreneurRoute:
      AuthenticatedDashboardEntrepreneurRoute,
    AuthenticatedDashboardManagerRoute: AuthenticatedDashboardManagerRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedSessionsIdRouteChildren {
  AuthenticatedSessionsIdEditRoute: typeof AuthenticatedSessionsIdEditRoute
}

const AuthenticatedSessionsIdRouteChildren: AuthenticatedSessionsIdRouteChildren =
  {
    AuthenticatedSessionsIdEditRoute: AuthenticatedSessionsIdEditRoute,
  }

const AuthenticatedSessionsIdRouteWithChildren =
  AuthenticatedSessionsIdRoute._addFileChildren(
    AuthenticatedSessionsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRouteWithChildren
  AuthenticatedSessionsCreateRoute: typeof AuthenticatedSessionsCreateRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRouteWithChildren,
  AuthenticatedSessionsCreateRoute: AuthenticatedSessionsCreateRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
