/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedLayoutRouteImport } from './routes/_authenticated/_layout'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSessionsIndexRouteImport } from './routes/_authenticated/sessions/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedGoalsIndexRouteImport } from './routes/_authenticated/goals/index'
import { Route as AuthenticatedSettingsOrganizationRouteImport } from './routes/_authenticated/settings/organization'
import { Route as AuthenticatedSessionsCreateRouteImport } from './routes/_authenticated/sessions/create'
import { Route as AuthenticatedSessionsIdRouteImport } from './routes/_authenticated/sessions/$id'
import { Route as AuthenticatedDashboardManagerRouteImport } from './routes/_authenticated/dashboard/manager'
import { Route as AuthenticatedDashboardEntrepreneurRouteImport } from './routes/_authenticated/dashboard/entrepreneur'
import { Route as AuthenticatedDashboardCoachRouteImport } from './routes/_authenticated/dashboard/coach'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard/analytics'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedSessionsIdEditRouteImport } from './routes/_authenticated/sessions/$id.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLayoutRoute = AuthenticatedLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSessionsIndexRoute =
  AuthenticatedSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGoalsIndexRoute = AuthenticatedGoalsIndexRouteImport.update({
  id: '/goals/',
  path: '/goals/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsOrganizationRoute =
  AuthenticatedSettingsOrganizationRouteImport.update({
    id: '/settings/organization',
    path: '/settings/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsCreateRoute =
  AuthenticatedSessionsCreateRouteImport.update({
    id: '/sessions/create',
    path: '/sessions/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsIdRoute = AuthenticatedSessionsIdRouteImport.update({
  id: '/sessions/$id',
  path: '/sessions/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardManagerRoute =
  AuthenticatedDashboardManagerRouteImport.update({
    id: '/dashboard/manager',
    path: '/dashboard/manager',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardEntrepreneurRoute =
  AuthenticatedDashboardEntrepreneurRouteImport.update({
    id: '/dashboard/entrepreneur',
    path: '/dashboard/entrepreneur',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardCoachRoute =
  AuthenticatedDashboardCoachRouteImport.update({
    id: '/dashboard/coach',
    path: '/dashboard/coach',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/dashboard/analytics',
    path: '/dashboard/analytics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/dashboard/admin',
    path: '/dashboard/admin',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSessionsIdEditRoute =
  AuthenticatedSessionsIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSessionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/dashboard/entrepreneur': typeof AuthenticatedDashboardEntrepreneurRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRouteWithChildren
  '/sessions/create': typeof AuthenticatedSessionsCreateRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/sessions/$id/edit': typeof AuthenticatedSessionsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/dashboard/entrepreneur': typeof AuthenticatedDashboardEntrepreneurRoute
  '/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/sessions/$id': typeof AuthenticatedSessionsIdRouteWithChildren
  '/sessions/create': typeof AuthenticatedSessionsCreateRoute
  '/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/goals': typeof AuthenticatedGoalsIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/sessions': typeof AuthenticatedSessionsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/sessions/$id/edit': typeof AuthenticatedSessionsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/_layout': typeof AuthenticatedLayoutRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/login': typeof AuthLoginRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/coach': typeof AuthenticatedDashboardCoachRoute
  '/_authenticated/dashboard/entrepreneur': typeof AuthenticatedDashboardEntrepreneurRoute
  '/_authenticated/dashboard/manager': typeof AuthenticatedDashboardManagerRoute
  '/_authenticated/sessions/$id': typeof AuthenticatedSessionsIdRouteWithChildren
  '/_authenticated/sessions/create': typeof AuthenticatedSessionsCreateRoute
  '/_authenticated/settings/organization': typeof AuthenticatedSettingsOrganizationRoute
  '/_authenticated/goals/': typeof AuthenticatedGoalsIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/sessions/': typeof AuthenticatedSessionsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/sessions/$id/edit': typeof AuthenticatedSessionsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/profile'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/coach'
    | '/dashboard/entrepreneur'
    | '/dashboard/manager'
    | '/sessions/$id'
    | '/sessions/create'
    | '/settings/organization'
    | '/goals'
    | '/payments'
    | '/sessions'
    | '/users'
    | '/sessions/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/profile'
    | '/auth/login'
    | '/dashboard/admin'
    | '/dashboard/analytics'
    | '/dashboard/coach'
    | '/dashboard/entrepreneur'
    | '/dashboard/manager'
    | '/sessions/$id'
    | '/sessions/create'
    | '/settings/organization'
    | '/goals'
    | '/payments'
    | '/sessions'
    | '/users'
    | '/sessions/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/_layout'
    | '/_authenticated/profile'
    | '/auth/login'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/coach'
    | '/_authenticated/dashboard/entrepreneur'
    | '/_authenticated/dashboard/manager'
    | '/_authenticated/sessions/$id'
    | '/_authenticated/sessions/create'
    | '/_authenticated/settings/organization'
    | '/_authenticated/goals/'
    | '/_authenticated/payments/'
    | '/_authenticated/sessions/'
    | '/_authenticated/users/'
    | '/_authenticated/sessions/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_layout': {
      id: '/_authenticated/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedLayoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/': {
      id: '/_authenticated/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthenticatedSessionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals/': {
      id: '/_authenticated/goals/'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/organization': {
      id: '/_authenticated/settings/organization'
      path: '/settings/organization'
      fullPath: '/settings/organization'
      preLoaderRoute: typeof AuthenticatedSettingsOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/create': {
      id: '/_authenticated/sessions/create'
      path: '/sessions/create'
      fullPath: '/sessions/create'
      preLoaderRoute: typeof AuthenticatedSessionsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$id': {
      id: '/_authenticated/sessions/$id'
      path: '/sessions/$id'
      fullPath: '/sessions/$id'
      preLoaderRoute: typeof AuthenticatedSessionsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/manager': {
      id: '/_authenticated/dashboard/manager'
      path: '/dashboard/manager'
      fullPath: '/dashboard/manager'
      preLoaderRoute: typeof AuthenticatedDashboardManagerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/entrepreneur': {
      id: '/_authenticated/dashboard/entrepreneur'
      path: '/dashboard/entrepreneur'
      fullPath: '/dashboard/entrepreneur'
      preLoaderRoute: typeof AuthenticatedDashboardEntrepreneurRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/coach': {
      id: '/_authenticated/dashboard/coach'
      path: '/dashboard/coach'
      fullPath: '/dashboard/coach'
      preLoaderRoute: typeof AuthenticatedDashboardCoachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sessions/$id/edit': {
      id: '/_authenticated/sessions/$id/edit'
      path: '/edit'
      fullPath: '/sessions/$id/edit'
      preLoaderRoute: typeof AuthenticatedSessionsIdEditRouteImport
      parentRoute: typeof AuthenticatedSessionsIdRoute
    }
  }
}

interface AuthenticatedSessionsIdRouteChildren {
  AuthenticatedSessionsIdEditRoute: typeof AuthenticatedSessionsIdEditRoute
}

const AuthenticatedSessionsIdRouteChildren: AuthenticatedSessionsIdRouteChildren =
  {
    AuthenticatedSessionsIdEditRoute: AuthenticatedSessionsIdEditRoute,
  }

const AuthenticatedSessionsIdRouteWithChildren =
  AuthenticatedSessionsIdRoute._addFileChildren(
    AuthenticatedSessionsIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedLayoutRoute: typeof AuthenticatedLayoutRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardCoachRoute: typeof AuthenticatedDashboardCoachRoute
  AuthenticatedDashboardEntrepreneurRoute: typeof AuthenticatedDashboardEntrepreneurRoute
  AuthenticatedDashboardManagerRoute: typeof AuthenticatedDashboardManagerRoute
  AuthenticatedSessionsIdRoute: typeof AuthenticatedSessionsIdRouteWithChildren
  AuthenticatedSessionsCreateRoute: typeof AuthenticatedSessionsCreateRoute
  AuthenticatedSettingsOrganizationRoute: typeof AuthenticatedSettingsOrganizationRoute
  AuthenticatedGoalsIndexRoute: typeof AuthenticatedGoalsIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedSessionsIndexRoute: typeof AuthenticatedSessionsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLayoutRoute: AuthenticatedLayoutRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
  AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
  AuthenticatedDashboardCoachRoute: AuthenticatedDashboardCoachRoute,
  AuthenticatedDashboardEntrepreneurRoute:
    AuthenticatedDashboardEntrepreneurRoute,
  AuthenticatedDashboardManagerRoute: AuthenticatedDashboardManagerRoute,
  AuthenticatedSessionsIdRoute: AuthenticatedSessionsIdRouteWithChildren,
  AuthenticatedSessionsCreateRoute: AuthenticatedSessionsCreateRoute,
  AuthenticatedSettingsOrganizationRoute:
    AuthenticatedSettingsOrganizationRoute,
  AuthenticatedGoalsIndexRoute: AuthenticatedGoalsIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedSessionsIndexRoute: AuthenticatedSessionsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
